Scrum 15 cut durchfuehren 2
AndreasJuergensen/Programmiersysteme-Osten pull request #31
Opened 2024-12-19 19:08 UTC by NKfabi

Branch wird mit aktuellem Stand gemerged.

Die Funktion des noch zu erstellenden Kanten-Sammel-Service wird im Nachgang ergänzt.

2024-12-19 20:05 UTC, NKfabi commented
Musste leider feststellen, dass der Aufruf des FeedbackService im Test des ExecuteCut-Service zu Problemen führt.

2024-12-20 19:02 UTC, haiddablitz requested changes
Siehe zwei Kommentare in `execute-cut.service.spec.ts`. Ansonsten passt das für mich soweit.

2024-12-20 19:02 UTC, haiddablitz commented on src/app/services/execute-cut.service.spec.ts
> +    let mockedFoo: ShowFeedbackService = mock(ShowFeedbackService);
Statt `mockedFoo` würde hier eher `showFeedbackServiceMock` passen.

2024-12-20 19:02 UTC, haiddablitz commented on src/app/services/execute-cut.service.spec.ts
> +    let foo: ShowFeedbackService = instance(mockedFoo);
Analog zu oben `showFeedbackServiceMockInstance`.

2024-12-20 19:37 UTC, fehle requested changes

2024-12-20 19:37 UTC, fehle commented on src/app/services/petri-net-management.service.ts
> +        this.updatePn();
Hab ich heute gesehen als ich mich mit den Fall Throughs beschäftigt habe. Hat der Selbst-Aufruf eine Funktion?

2024-12-20 20:56 UTC, NKfabi commented on src/app/services/execute-cut.service.spec.ts
> +    let foo: ShowFeedbackService = instance(mockedFoo);
Pass ich beides an.

2024-12-20 20:58 UTC, NKfabi commented on src/app/services/petri-net-management.service.ts
> +        this.updatePn();
Meinst du Zeile 2 der Methode? this.updatePn()?

2024-12-20 21:20 UTC, fehle commented on src/app/services/petri-net-management.service.ts
> +        this.updatePn();
Ja genau

2024-12-20 21:35 UTC, NKfabi commented on src/app/services/petri-net-management.service.ts
> +        this.updatePn();
Gute Frage. Denke tatsächlich, dass man es nicht braucht.

2024-12-20 21:40 UTC, fehle commented on src/app/services/petri-net-management.service.ts
> +        this.updatePn();
Na wenn du es nicht weißt...

2024-12-21 13:57 UTC, fehle approved these changes

2024-12-22 09:51 UTC, haiddablitz approved these changes

2024-12-22 10:12 UTC, merged